language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y "deb http://ppa.launchpad.net/grilo-team/travis/ubuntu trusty main"
  - sudo add-apt-repository -y "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common libjson-glib-dev libsoup2.4-dev libgrilo-0.2-dev libsqlite3-dev liboauth-dev lcov libdmapsharing-3.0-dev libgmime-2.6-dev libtracker-sparql-0.16-dev libgssdp-1.0-dev libgupnp-1.0-dev libgupnp-av-1.0-dev libquvi-dev libtotem-plparser-dev libgdata-dev yelp-tools libavahi-gobject-dev python-dbusmock zlib1g-dev libgom libmediaart-1.0-dev liblua5.2-dev
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - ./autogen.sh --enable-gcov
  - make
  - make check
after_success:
  - coveralls --exclude tests --exclude help
